# Generated by Django 2.2 on 2019-04-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190410_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='time_m',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
