# Generated by Django 2.2 on 2019-04-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190410_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_schedule', models.ManyToManyField(to='app.Schedule')),
            ],
        ),
    ]
