# Generated by Django 2.2 on 2019-04-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_workerschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerSchedule',
        ),
    ]
